name: Saudações

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Olá, dev! Estou vendo que essa é sua primeira issue no repo. Seja muito-bem vindo(a)!'
        pr-message: 'Primeira PR no repo, certo? Lembre-se de detalhar bem o que foi feito ;)'
